/* ============================================================
   jobs.jsx — open positions + full job descriptions
   Content taken verbatim in substance from the client's JD documents.
   Consumed by careers.jsx (listing + detail) and by the application
   form's role dropdown.
   ============================================================ */
const CAREER_ROLES = [
  {
    id:"project-manager",
    role:"Project Manager / Sr. Project Manager",
    team:"Projects", loc:"Bangalore", exp:"5+ years", type:"Full-time",
    reports:"Project Head",
    blurb:"End-to-end project delivery — timely completion, cost efficiency, site readiness, vendor coordination and statutory compliance.",
    purpose:"The Project Manager – Execution is responsible for end-to-end project delivery, ensuring timely completion, cost efficiency, site readiness, vendor coordination, and compliance with statutory and safety requirements. The role demands strong execution capability, cross-functional coordination, and adherence to defined project KPIs.",
    groups:[
      { h:"Timely project delivery", items:[
        "Ensure project commissioning on or before defined deadlines",
        "Monitor project timelines and proactively mitigate delays",
        "Track progress based on MW delivery targets",
        "Coordinate with internal and external stakeholders to resolve execution challenges",
        "Adjust timelines considering approved client-related delays",
      ]},
      { h:"Budget adherence", items:[
        "Ensure project execution within the approved budget",
        "Monitor cost variance between planned and actual expenses",
        "Optimize costs without compromising quality and timelines",
        "Work closely with finance and procurement teams for cost control",
        "Ensure adherence to the latest approved project budget",
      ]},
      { h:"Site readiness & handover", items:[
        "Ensure all sites are fully prepared for commissioning",
        "Oversee documentation and ensure proper handover within 30 days of commissioning",
        "Coordinate with site teams to maintain readiness standards",
        "Ensure all required reports and documentation are complete and accurate",
      ]},
      { h:"Vendor / contractor coordination", items:[
        "Manage vendors and contractors for timely material delivery and execution",
        "Ensure critical path materials are delivered without delays",
        "Monitor vendor performance and address issues proactively",
        "Collaborate with the procurement team for efficient vendor management",
      ]},
      { h:"Approvals & compliance", items:[
        "Ensure timely completion of all statutory approvals",
        "Coordinate with liaisoning teams for regulatory clearances",
        "Ensure all safety audits are conducted and passed as per standards",
        "Maintain compliance with project timelines and regulatory requirements",
      ]},
      { h:"Liaisoning & audit support", items:[
        "Track approval timelines and ensure adherence",
        "Support safety and compliance audits",
        "Ensure audit readiness and 100% compliance where required",
        "Maintain proper documentation for approvals and audits",
      ]},
    ],
    quals:[
      "Bachelor's degree in Engineering (Electrical / Mechanical / Civil preferred)",
      "5+ years of experience in project execution (renewable energy / infrastructure preferred)",
      "Proven experience in managing the end-to-end project lifecycle",
    ],
    skills:["Project planning & execution","Cost control & budget management","Vendor & stakeholder management","Strong communication & coordination","Knowledge of statutory approvals & compliance","Problem-solving and decision-making"],
    preferred:["Solar / wind / renewable energy projects","Infrastructure / project delivery"],
  },
  {
    id:"state-head-sales",
    role:"State Head – Sales & Business Development",
    team:"Sales", loc:"Karnataka, Maharashtra", exp:"6–8 years", type:"Full-time",
    blurb:"Own the entire state P&L — pipeline, closures, customer relationships, government and DISCOM relations, MW signed and ₹/kWh realised.",
    purpose:"Owns the entire state P&L — pipeline, closures, customer relationships, government/DISCOM relations, and ultimately MW signed and ₹/kWh realised. One per state.",
    groups:[
      { h:"Key responsibilities", items:[
        "Build a 100–150 MW/year pipeline in their state",
        "Own top-25 named accounts personally at CXO level",
        "Manage Junior Solution Architects & Sales Development Representative coverage in the state",
        "Coordinate State Nodal Agency, DISCOM and SLDC relationships in their state",
        "Negotiate complex Group Captive SPV structures",
        "Represent Integrum at state-level CII, FICCI, ASSOCHAM, KASSIA / MCCIA / CODISSIA chapters",
        "Lead post-PPA escalation handling",
        "Quarterly competitor scans",
      ]},
    ],
    quals:[
      "B.E. preferred; 6–8 years total, with 3+ in C&I solar B2B sales in that specific state",
      "Demonstrably closed 50+ MW of open-access / captive deals in the target state",
      "Network of 50+ named CXO contacts in the state's top 200 corporates",
      "Local language fluency strongly preferred",
    ],
    skills:["State P&L ownership","Group Captive SPV structuring","CXO-level relationship management","Government & DISCOM liaison"],
    preferred:["Resident of the state capital with 5+ years' tenure","Prior sales leadership across a sizeable geographic region in C&I renewables"],
    profile:"Someone who is already the de facto sales leader for their state at a competitor, but is being held back by HQ-driven pricing or a founder who controls the big deals. Wants state-level P&L ownership and the freedom to build their own team.",
  },
  {
    id:"bdm",
    role:"Manager / Sr Manager / AVP – Business Development",
    team:"Sales", loc:"Bangalore", exp:"7–15 years", type:"Full-time",
    reports:"President – Sales",
    blurb:"Business development for C&I consumers in Karnataka across wind, solar and wind-solar hybrid — CAPEX and OPEX solutions.",
    purpose:"It is important that the candidate has at least one of the following capabilities: IPP wind / solar sale; solar / wind project CAPEX sale; power trading and power solutions; or capital goods / industrial CAPEX sale with industrial consumer relationships in the target market.",
    groups:[
      { h:"Key deliverables", items:[
        "Carry out business development for Commercial and Industrial (C&I) consumers in the Karnataka region for wind, solar and wind-solar hybrid — CAPEX and OPEX solutions",
        "Generate leads and opportunities",
        "Keep track of competition",
        "Improve current market penetration, generating new business opportunities, deal closure and customer relationship management",
        "Keep track of regulations in Karnataka and drive relationships therein",
      ]},
    ],
    quals:["Minimum BE / BTech; MBA will be a plus","7 to 15 years' experience"],
    skills:[
      "Proven track record in a BD role for industrial products / projects / solution sales to C&I consumers in Karnataka; exposure to other southern states a plus",
      "Excellent networking and communication skills",
      "Experience managing customers across Karnataka",
      "Comfortable in a highly agile environment",
      "Excellent negotiation and convincing skills",
    ],
  },
  {
    id:"power-sales-trading",
    role:"Manager / Senior Manager / Head – Power Sales & Trading",
    team:"Power Sales & Trading", loc:"Bangalore", exp:"5–10 years", type:"Full-time",
    reports:"CXO group",
    blurb:"Lead power-sales origination, trading operations and digital energy management on Integrum's PowerEdge platform.",
    purpose:"The incumbent will lead power-sales origination, trading operations, and digital energy management using the Integrum PowerEdge platform. The role blends commercial, analytical and technological capabilities to optimise trading performance, client savings and platform adoption.",
    groups:[
      { h:"Power sales & origination", items:[
        "Identify and close power-sourcing opportunities under group-captive, bilateral, exchange or virtual-PPA models",
        "Engage industrial and commercial clients with renewable power-supply and cost-optimisation solutions",
        "Structure and negotiate commercial offers considering tariff benchmarks, open-access charges and RE mix",
        "Manage client engagement from proposal through execution, ensuring compliance with open-access and regulatory frameworks",
        "Liaise with legal, finance and asset-operations teams for seamless deal delivery",
      ]},
      { h:"Trading & portfolio management", items:[
        "Execute trades on IEX / PXIL and through OTC bilateral contracts to optimise Integrum's and clients' portfolios",
        "Use PowerEdge dashboards to monitor day-ahead and real-time positions, DSM exposure, congestion and deviation costs",
        "Manage scheduling, forecasting and balancing obligations for captive and third-party clients",
        "Optimise green certificate and carbon trading opportunities for clients",
        "Continuously identify margin-improvement and cost-saving opportunities",
      ]},
      { h:"Platform development — Integrum PowerEdge", items:[
        "Define functional requirements with the technology and analytics teams: data capture from generation (SCADA), scheduling and SLDC systems",
        "Development of forecasting and predictive modules",
        "Integration of trading positions, DSM analytics and dashboards",
        "Portfolio reporting, alerts and client-facing modules",
        "Act as the business-side anchor for testing, validating and refining the PowerEdge prototype, and support UAT",
        "Lead initial pilot deployments for internal or select client portfolios",
      ]},
      { h:"Analytics, risk & reporting", items:[
        "Build and maintain commercial models for pricing, trading margins, DSM impact and client savings",
        "Track traded volumes, cost optimisation, forecast accuracy and risk mitigation",
        "Generate MIS, dashboards and insights that feed into PowerEdge analytics",
      ]},
    ],
    quals:[
      "Bachelor's degree in Engineering / Energy / Economics / Finance",
      "5–10 years' experience in power trading, open-access sales or energy portfolio management",
      "Understanding of Indian power markets, REC trading and DSM regulations",
      "Strong analytical and negotiation skills; proficiency in Excel and Power BI",
      "Familiarity with energy-management or trading-software platforms (EMS / ETRM)",
    ],
    skills:["Power trading (IEX / PXIL, OTC)","Open-access & group-captive structuring","Forecasting & scheduling","DSM analytics","Commercial modelling"],
    preferred:[
      "MBA / Master's in Energy Management or Finance",
      "Prior experience using or developing digital energy-management systems",
      "Exposure to AI/ML-based forecasting, RE dispatch and energy data analytics",
    ],
  },
  {
    id:"liaison-officer",
    role:"DISCOM Liaison Officer",
    team:"Sales", loc:"Karnataka / Maharashtra", exp:"2–5 years", type:"Full-time",
    blurb:"Own meter name transfers, ABT/smart-meter upgrades and contract demand management at DISCOM offices — one per state.",
    purpose:"Solves the single most common on-ground delay in onboarding leased-premises industrial and commercial customers: converting the DISCOM electricity connection and meter ownership from landlord to tenant, and getting the mandatory ToD / Special Energy Meter installed and commissioned quickly. This sits between Sales and Regulatory, but is fundamentally a boots-on-the-ground DISCOM-counter role, not a desk-based compliance role. One per state, with Karnataka and Maharashtra hired first.",
    groups:[
      { h:"Key responsibilities", items:[
        "Own the end-to-end electricity-connection name-transfer process at BESCOM / ESCOM divisional offices (Karnataka) and MSEDCL / TPC-D / AEML circle offices (Maharashtra)",
        "Prepare and file the complete transfer application packet per customer — lease deed, landlord NOC, company KYC, board resolution, prior consumption history — and track it through to approval",
        "Work closely with third-party vendors to close conversions in a timely manner, understanding barrier points and helping vendors overcome them",
        "Manage relationships with local DISCOM Assistant Executive Engineers, Executive Engineers and sub-division / section offices",
        "Coordinate installation and commissioning of the mandatory ToD / Special Energy Meter at each customer site, including joint meter reading where required",
        "Where a connection must move from LT to HT, or sanctioned load needs enhancement to clear the 100 kW threshold, initiate and follow through that application in parallel",
        "Maintain a live, site-by-site tracker shared with Sales, Solution Architects and the Regulatory Lead",
        "Escalate stuck files through the correct DISCOM escalation ladder rather than letting a file sit un-actioned",
        "Build and maintain working relationships with DISCOM officials, meter vendors and empanelled electrical contractors in their state",
        "Flag recurring bottlenecks to the Regulatory Lead and VP Sales so systemic issues can be raised at a policy level",
        "Support the Solution Architect with site-level technical documentation required by the DISCOM",
        "Document and continuously update the SOP for meter ownership and meter type conversion",
      ]},
    ],
    quals:[
      "Graduates in any field with strong DISCOM / government-liaisoning experience preferred; a Diploma in Electrical Engineering is a plus but not mandatory",
      "2–5 years of hands-on experience liaisoning directly with DISCOM divisional / circle offices",
      "Demonstrated track record of getting connection transfers, load enhancements or new connections approved",
      "Working knowledge of the state's DISCOM organisational structure and the document checklist for name transfer and metering",
      "Comfortable with high-frequency, in-person government-office visits — this is not a desk job",
      "Local language fluency (Kannada for Karnataka; Marathi for Maharashtra) is a strong requirement",
    ],
    skills:["DISCOM liaison","Name transfer & metering applications","ToD / SEM commissioning","Escalation management"],
    preferred:[
      "Prior experience with commercial / HT connections — hospitals, hotels, malls, office parks",
      "Existing relationships with AEE / EE-level officials in the target divisions",
      "Experience coordinating with empanelled meter vendors or AMISP agencies",
      "Prior stint at a solar project developer, C&I developer or facilities management firm in a connection-liaisoning capacity",
    ],
    profile:"Someone who is fundamentally a 'gets things done at the government counter' operator — patient, persistent, and genuinely well-liked by DISCOM staff because they show up prepared, follow up politely but relentlessly, and don't waste officials' time. Motivated by seeing a file move from stuck for three months to cleared in three weeks.",
  },
  {
    id:"sales-executive",
    role:"Executive – Sales",
    team:"Sales", loc:"Bangalore, then Maharashtra / Gujarat / Karnataka", exp:"2–5 years", type:"Full-time",
    blurb:"Generate leads, close sales and build client relationships across our energy products and services.",
    purpose:"We are seeking a motivated and results-driven salesperson. The ideal candidate will generate leads, close sales and maintain strong client relationships, promoting and selling our energy products and services and contributing to the overall growth of the company. Initial six-month training in Bangalore, followed by deployment in Maharashtra, Gujarat or Karnataka as per business requirements.",
    groups:[
      { h:"Key responsibilities", items:[
        "Identify and engage potential customers through various sales channels",
        "Present and promote company solutions and services to prospective clients",
        "Build and maintain strong relationships with new and existing customers",
        "Meet or exceed monthly and quarterly sales targets",
        "Conduct market research to identify new sales opportunities and competitor activity",
        "Follow up with clients to ensure satisfaction and address concerns",
        "Collaborate with the sales team to develop effective strategies",
        "Maintain accurate records of sales activities and client interactions in CRM software",
      ]},
    ],
    quals:["Bachelor's degree in Engineering and MBA"],
    skills:["Strong negotiation and closing skills","Excellent verbal and written communication","Ability to work independently and in a team","Customer-oriented, problem-solving mindset"],
    preferred:["Competitive salary and incentive structure","Opportunities for career growth and professional development"],
  },
  {
    id:"green-homes-bd",
    role:"Business Development – Green Homes",
    team:"Sales", loc:"Bangalore", exp:"5–10 years", type:"Full-time",
    blurb:"Develop the Green Homes business — customer solutions, technical sales and partner relationships.",
    purpose:"Develop Integrum's Green Homes business, covering customer solutions, technical sales and channel partner relationships.",
    groups:[
      { h:"Key responsibilities", items:[
        "Build and convert the Green Homes pipeline across target micro-markets",
        "Develop customer solutions and lead technical sales conversations",
        "Establish and manage channel and partner relationships",
        "Track competition, pricing and regulation relevant to the segment",
      ]},
    ],
    quals:["Graduate; engineering background preferred","5–10 years in techno-commercial sales, ideally in energy, building products or allied sectors"],
    skills:["Techno-commercial sales","Customer solutioning","Channel development"],
    jdPending:true,
  },
  {
    id:"site-incharge",
    role:"Site Incharge",
    team:"Projects", loc:"Maharashtra & Karnataka", exp:"8–10 years", type:"Full-time",
    blurb:"Own day-to-day site delivery, contractor coordination and safety compliance at an operating project site.",
    purpose:"Own day-to-day delivery at an operating project site, coordinating contractors and ensuring safety and quality compliance through to commissioning.",
    groups:[
      { h:"Key responsibilities", items:[
        "Run daily site execution against the approved schedule",
        "Coordinate contractors, material movement and manpower at site",
        "Maintain safety, quality and statutory compliance on site",
        "Report progress, risks and deviations to the project manager",
      ]},
    ],
    quals:["Diploma or degree in Engineering","8–10 years of site execution experience in renewables or infrastructure"],
    skills:["Site execution","Contractor management","Safety compliance"],
    jdPending:true,
  },
  {
    id:"safety-officer",
    role:"Safety Officer",
    team:"Projects", loc:"BBV / Nandurbar", exp:"1–5 years", type:"Full-time",
    blurb:"Implement and audit site safety systems, permits and training across construction and commissioning.",
    purpose:"Implement and audit site safety systems across construction and commissioning activity, ensuring every site meets statutory and internal safety standards.",
    groups:[
      { h:"Key responsibilities", items:[
        "Implement site safety plans, permits to work and toolbox talks",
        "Conduct safety inductions and training for site teams and contractors",
        "Carry out safety audits and close observations to completion",
        "Investigate incidents and maintain safety documentation and reporting",
      ]},
    ],
    quals:["Diploma or degree with a recognised industrial safety qualification","1–5 years in construction or renewables site safety"],
    skills:["Site safety systems","Safety audits","Incident investigation"],
    jdPending:true,
  },
  {
    id:"ca-fresher",
    role:"Chartered Accountant – Fresher",
    team:"Finance & Accounts", loc:"Koramangala, Bangalore", exp:"0–1 year", type:"Full-time",
    reports:"Head F&A / CFO",
    blurb:"Accounting, financial reporting, taxation and audit support across a capital-intensive renewables portfolio.",
    purpose:"Support day-to-day accounting, financial reporting, taxation and audit across Integrum's renewable energy portfolio, with end-to-end exposure to finance, strategy and sustainability.",
    groups:[
      { h:"Accounting & bookkeeping", items:[
        "Manage daily accounting operations including journal entries, ledger scrutiny and reconciliations",
        "Ensure timely closure of books on a monthly, quarterly and annual basis",
        "Maintain accuracy of the general ledger across asset, liability, revenue and expense entries",
      ]},
      { h:"Financial reporting", items:[
        "Assist in preparation of monthly, quarterly and annual financial statements",
        "Ensure compliance with applicable accounting standards (IND-AS / IFRS)",
        "Coordinate with internal teams for accurate and timely reporting",
      ]},
      { h:"Taxation & compliance", items:[
        "Ensure timely filing of GST, TDS, income tax and other statutory returns",
        "Support tax assessments and audits, and liaise with tax consultants",
        "Maintain the compliance tracker and documentation for all statutory filings",
      ]},
      { h:"Audit support", items:[
        "Assist in statutory, internal, cost and tax audits by preparing audit schedules and documentation",
        "Implement audit recommendations and ensure internal controls are followed",
      ]},
    ],
    quals:[
      "Recently qualified Chartered Accountant, 0–1 year experience",
      "Strong knowledge of financial concepts — IRR, NPV, cash flow analysis, P&L, balance sheet",
      "Proficiency in Microsoft Excel and PowerPoint",
      "High attention to detail and an analytical mindset",
      "Strong communication skills and the ability to work cross-functionally",
    ],
    skills:["Accounting & book closure","IND-AS / IFRS reporting","GST, TDS & income tax","Audit support","Financial modelling"],
    preferred:[
      "Exposure to financial modelling in renewable energy, infrastructure or related sectors",
      "Articleship experience in audit, financial advisory or FP&A",
    ],
  },
  {
    id:"company-secretary",
    role:"Company Secretary – IPO & Compliance",
    team:"Finance & Accounts", loc:"Bangalore", exp:"2–5 years", type:"Full-time",
    blurb:"Secretarial compliance, corporate governance and IPO-related activity as the company scales.",
    purpose:"We are looking for a qualified Company Secretary with knowledge and experience in IPO processes, corporate governance and regulatory compliance. The candidate will ensure compliance with statutory and regulatory requirements and assist in IPO-related activities.",
    groups:[
      { h:"Key responsibilities", items:[
        "Assist in IPO planning, documentation and coordination with merchant bankers, legal advisors and regulatory authorities",
        "Ensure compliance with SEBI, the Companies Act and stock exchange regulations",
        "Prepare and file ROC forms, annual returns and statutory documents",
        "Maintain statutory registers and minutes of Board, Committee and General Meetings",
        "Draft Board resolutions, agendas and minutes",
        "Coordinate with internal teams and external consultants for IPO due diligence and documentation",
        "Ensure compliance with corporate governance standards and regulatory requirements",
        "Handle secretarial audits, compliance reports and regulatory filings",
        "Support management in corporate restructuring, share allotments and investor relations",
      ]},
    ],
    quals:[
      "Qualified Company Secretary from the Institute of Company Secretaries of India (ICSI)",
      "Strong knowledge of the Companies Act, SEBI regulations and the IPO process",
    ],
    skills:["IPO process & SEBI regulations","Excellent drafting and communication","Attention to detail, compliance-oriented","Multi-stakeholder coordination"],
  },
];

Object.assign(window, { CAREER_ROLES });
